Repository wp-cli/wp-config-transformer, pull requests merged in 2023-04, with the labels that each got.

#41 Avoid test failure with `assertNotSame` instead of `assertNotEquals`
  tests/2-UpdateTest.php
  tests/3-BlockTest.php
  tests/4-MultilineTest.php
Labels: scope:testing

#42 Allow `johnpbloch/wordpress-core-installer`
  composer.json
Labels: scope:distribution

#43 Fix incorrect return type in docblock for get_value()
  src/WPConfigTransformer.php
Labels: scope:documentation
